/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    menu: Menu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ka') | ('en' | 'ka')[];
  globals: {
    'home-view': HomeView;
    'layout-view': LayoutView;
  };
  globalsSelect: {
    'home-view': HomeViewSelect<false> | HomeViewSelect<true>;
    'layout-view': LayoutViewSelect<false> | LayoutViewSelect<true>;
  };
  locale: 'en' | 'ka';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * ატვირთეთ სურათები თქვენი საიტისთვის
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * სურათის აღწერა accessibility-სთვის
   */
  alt?: string | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name: string;
  desc: string;
  price: number;
  image: string | Media;
  /**
   * მენიუ სავალდებულოა მხოლოდ VIP, პრემიუმი ან სტანდარტული ევენთებზე
   */
  menu?: {
    food_menu_name: string;
    drink_menu_name: string;
    list: {
      menu: string | Menu;
      id?: string | null;
    }[];
  };
  /**
   * პაკეტების ჩამონათვალი სავალდებულოა მხოლოდ VIP, პრემიუმი ან სტანდარტული ევენთებზე
   */
  packages?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ხელის თხოვნის პაკეტების ჩამონათვალი სავალდებულოა მხოლოდ (გულის ფორმის წინადადებების დეკორაცია, სადღესასწაულოდ მორთული სუფრა, წინადადებების ცერემონია ნავზე) ევენთებზე
   */
  proposal_packages?: {
    name: string;
    list?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    text: string;
  };
  package:
    | 'VIP'
    | 'premium'
    | 'standard'
    | 'Heart_Shaped_Proposal_Decoration'
    | 'Festively_Decorated_Table'
    | 'Proposal_Ceremony_on_the_Boat';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  type: 'dish' | 'drink';
  name: string;
  desc: string;
  price: number;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  desc?: T;
  price?: T;
  image?: T;
  menu?:
    | T
    | {
        food_menu_name?: T;
        drink_menu_name?: T;
        list?:
          | T
          | {
              menu?: T;
              id?: T;
            };
      };
  packages?:
    | T
    | {
        name?: T;
        id?: T;
      };
  proposal_packages?:
    | T
    | {
        name?: T;
        list?:
          | T
          | {
              name?: T;
              id?: T;
            };
        text?: T;
      };
  package?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  desc?: T;
  price?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-view".
 */
export interface HomeView {
  id: string;
  hero: {
    images: {
      image: string | Media;
      id?: string | null;
    }[];
    title: string;
    subtitle: string;
    primary_btn: string;
    secondary_btn: string;
  };
  events: {
    /**
     * მაგ: Make Your Dream Event Come True
     */
    section_title: string;
    /**
     * ყველა ივენთი
     */
    events_list: {
      /**
       * ივენთის ბარათის სურათი (384x320px)
       */
      image: string | Media;
      /**
       * ივენთის სათაური
       */
      title: string;
      /**
       * ივენთის სრული აღწერა ბარათზე
       */
      text: string;
      btn: string;
      packages: {
        label: string;
        event: string | Event;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  about: {
    title: string;
    subtitle: string;
    images: {
      image: string | Media;
      id?: string | null;
    }[];
  };
  menu: {
    name: string;
    subname: string;
    menu_list: {
      menu: string | Menu;
      id?: string | null;
    }[];
  };
  boat_tours_section: {
    name: string;
    boat_tours: {
      side: 'left' | 'right';
      primary_btn: string;
      image: string | Media;
      name: string;
      details: {
        people_count: number;
        gift: string;
      };
      desc: string;
      full_rental: {
        title: string;
        list: {
          item: string;
          id?: string | null;
        }[];
      };
      group_tour: {
        /**
         * მაგ: Group Tour - Dolphin ( Minimum: 5 guests required )
         */
        title: string;
        tour_details: {
          icon: 'day' | 'night' | 'money' | 'time';
          /**
           * მაგ: Day - 17:00, Night - 21:00, 30₾/Per Guest, 30 Minute
           */
          text: string;
          id?: string | null;
        }[];
      };
      id?: string | null;
    }[];
  };
  gallery: {
    /**
     * გალერეის ფილტრის კატეგორიები
     */
    categories: {
      /**
       * მაგ: Restaurant Images, Water Transport, Events, Menu
       */
      name: string;
      images: {
        image: string | Media;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  contact: {
    header: {
      /**
       * მაგ: Reach Out to TIVI
       */
      title: string;
      /**
       * მაგ: Planning a visit or a river cruise? We're just a message away.
       */
      description: string;
    };
    info: {
      /**
       * მაგ: +995 578 761 982
       */
      phone: string;
      /**
       * მაგ: Everyday from 9:00 - to 23:00
       */
      working_hours: string;
      /**
       * სრული მისამართი
       */
      address: string;
    };
    social: {
      /**
       * სრული URL მაგ: https://facebook.com/tivi
       */
      facebook?: string | null;
      /**
       * სრული URL მაგ: https://instagram.com/tivi
       */
      instagram?: string | null;
    };
    map: {
      /**
       * Google Maps-დან აიღეთ Embed HTML კოდი და ჩასვით მხოლოდ src-ის URL
       */
      embed_url: string;
      /**
       * ოფციონალური - ლოკაციის დასახელება
       */
      location_name?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout-view".
 */
export interface LayoutView {
  id: string;
  navbar: {
    /**
     * ნავბარის ლოგო (SVG რეკომენდირებულია)
     */
    logo: string | Media;
    /**
     * მთავარი მენიუს ლინკები
     */
    navigation: {
      /**
       * მაგ: HOME, RESTAURANT, BOAT TOURS
       */
      label: string;
      /**
       * მაგ: #, #RESTAURANT, #BOAT-TOURS, /about
       */
      href: string;
      id?: string | null;
    }[];
    /**
     * სოციალური ქსელების ლინკები და იკონები
     */
    socials: {
      platform: 'facebook' | 'instagram' | 'whatsapp' | 'location' | 'twitter' | 'tiktok' | 'linkedin' | 'youtube';
      /**
       * SVG icon (24x24px)
       */
      icon: string | Media;
      /**
       * სრული URL მაგ: https://facebook.com/tivi
       */
      link: string;
      id?: string | null;
    }[];
  };
  footer: {
    /**
     * Footer-ის ლოგო სურათი
     */
    logo: string | Media;
    /**
     * Footer-ის მენიუს ლინკები
     */
    navigation: {
      /**
       * მაგ: HOME, RESTAURANT, BOAT TOURS
       */
      label: string;
      /**
       * მაგ: #, #RESTAURANT, #BOAT-TOURS ან https://example.com
       */
      href: string;
      /**
       * თუ ჩართულია, ლინკი გაიხსნება ახალ ტაბში
       */
      open_in_new_tab?: boolean | null;
      id?: string | null;
    }[];
    bottom: {
      /**
       * მაგ: All Rights Reserved, © 2024 TIVI
       */
      copyright: string;
      /**
       * ტექსტი დეველოპერის ლოგოს წინ
       */
      developer_text?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-view_select".
 */
export interface HomeViewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        title?: T;
        subtitle?: T;
        primary_btn?: T;
        secondary_btn?: T;
      };
  events?:
    | T
    | {
        section_title?: T;
        events_list?:
          | T
          | {
              image?: T;
              title?: T;
              text?: T;
              btn?: T;
              packages?:
                | T
                | {
                    label?: T;
                    event?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  menu?:
    | T
    | {
        name?: T;
        subname?: T;
        menu_list?:
          | T
          | {
              menu?: T;
              id?: T;
            };
      };
  boat_tours_section?:
    | T
    | {
        name?: T;
        boat_tours?:
          | T
          | {
              side?: T;
              primary_btn?: T;
              image?: T;
              name?: T;
              details?:
                | T
                | {
                    people_count?: T;
                    gift?: T;
                  };
              desc?: T;
              full_rental?:
                | T
                | {
                    title?: T;
                    list?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                  };
              group_tour?:
                | T
                | {
                    title?: T;
                    tour_details?:
                      | T
                      | {
                          icon?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        categories?:
          | T
          | {
              name?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  contact?:
    | T
    | {
        header?:
          | T
          | {
              title?: T;
              description?: T;
            };
        info?:
          | T
          | {
              phone?: T;
              working_hours?: T;
              address?: T;
            };
        social?:
          | T
          | {
              facebook?: T;
              instagram?: T;
            };
        map?:
          | T
          | {
              embed_url?: T;
              location_name?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout-view_select".
 */
export interface LayoutViewSelect<T extends boolean = true> {
  navbar?:
    | T
    | {
        logo?: T;
        navigation?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        socials?:
          | T
          | {
              platform?: T;
              icon?: T;
              link?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?: T;
        navigation?:
          | T
          | {
              label?: T;
              href?: T;
              open_in_new_tab?: T;
              id?: T;
            };
        bottom?:
          | T
          | {
              copyright?: T;
              developer_text?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}